### ISSUE TITLE
Build doesn't respect ARCHS build setting in cocoapods

### ISSUE THREAD

**Issue by silverhammermba** [apotocki/openssl-iosx#4]
Some of my cocoapods include arm64 simulator build support and some don't. To get a working simulator build on M1 I use `ARCHS[sdk=iphonesimulator*]` to force all pods to build for x86_64 simulator using Rosetta, like this:

```ruby
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      end
    end
  end
```

but your build script doesn't account for that variable. On my M1, the script only builds the arm64 simulator library, meaning I can no longer build for simulator (since some libs only have x86_64, and yours only has arm64).

How can I force this library to build for x86_64 simulator? I'm also investigating if I can get my other pods to build for arm64, but I'm not sure which approach will be more viable.

**Comment by apotocki** [comment]
Why don't you want to build x86 simulator binaries directly on x86_64 machine where you are going to start the simulator? 
The script builds simulator binaries only for the dev machine on purpose. I haven't seen a scenario when I need both (x86_64 and m1) simulator binaries in the same xcframework. When I work on x86_64 Mac, the script creates x86_64 binaries for the simulator and I run it with them. When I work on M1 Mac, the same script creates arm64 simulator binaries and I run it with them. So I don't see why somebody needs to create x86_64 simulator binaries on M1 or arm64 simulator binaries on Intel.

**Comment by silverhammermba** [comment]
You can run an x86_64 simulator on an M1 mac. Many of my pods have outdated build configs that don't work with M1 simulator, so to fix simulator builds on M1 I made all pods build for x86_64 simulator since that is what the outdated pods support.

**Comment by apotocki** [comment]
OK, I got your point. I could not even imagine that someone might need to run x86_64 simulator on arm64 architecture. I have changed the script a bit. Try version 1.1.1o.2

**Comment by lotz** [comment]
>I haven't seen a scenario when I need both (x86_64 and m1) simulator binaries in the same xcframework.

I have this scenario. I have a new M1-based MacBook Pro as well as an older Intel-based Mac mini for development. When I update/install `openssl-iosx` using Cocoapods, I do it on both machines and merge the configs and generated frameworks manually. I suppose I could run the `x86_64` simulator on my M1 MacBook Pro, but I'd rather run the `arm64` ones.

**Comment by apotocki** [comment]
@lotz, putting binaries in the git is not a good idea. If you avoid it you will not need to merge frameworks anymore.

**Comment by lotz** [comment]
Yep, fair point! I'll consider reworking things to avoid that. Thanks.

**Comment by silverhammermba** [comment]
@apotocki thanks for the quick patch! It looks like that might work for us, unfortunately we have not yet dropped support for iOS 12. Coincidentally I'm working on that now, so I should be able to test 1.1.1o.2 soon.
