### ISSUE TITLE
Fail to use it in Swift code

### ISSUE THREAD

**Issue by RMinibaev** [apotocki/openssl-iosx#5]
Hello, I'm facing an issue while trying to use this lib in my swift code.

I did import it in pod file with such line:
`pod 'openssl-iosx', '~> 1.1.1o.1'`

I found a way to use it in my Obj-C code by importing separate headers, ex.
`#import <openssl/x509.h>`

But when I add library import to .swift file, ex.
`import openssl` or `import openssl_iosx`
than compiler issue arise : 
> No such module 'openssl_iosx'

How can I use openssl code in swift files?

**Comment by apotocki** [comment]
The project just builds openssl static libraries. If you want to use it in Swift you need some bridging objective-c code. For details, you can start by exploring e.g. https://www.andrewcbancroft.com/2015/09/21/openssl-for-ios-swift-the-easy-way/

**Comment by RMinibaev** [comment]
Thanks, it seems to work! ❤️ 

Issue may be closed.
